/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/********************************************************************
* Description: config.h
*
*	Common defines used in many emc2 source files.
*       To add to this file, edit Section 4.1 in configure.in
*       and then run autoheader.
*
* Author: Autogenerated by autoheader
* License: LGPL Version 2
* System: Linux
*    
* Copyright (c) 2004 All rights reserved.
********************************************************************/
#ifndef EMC2_CONFIG_H
#define EMC2_CONFIG_H

/* LINELEN is used throughout for buffer sizes, length of file name strings,
   etc. Let's just have one instead of a multitude of defines all the same. */
#define LINELEN 255
/* Used in a number of places for sprintf() buffers. */
#define BUFFERLEN 80

#define MM_PER_INCH 25.4
#define INCH_PER_MM (1.0/25.4)


/* Directory for binaries */
#define EMC2_BIN_DIR "/home/lingchun/interpolation/temp/linuxcnc-mirror/bin"

/* Directory for configuration files */
#define EMC2_CONFIG_DIR ""

/* Default nml file */
#define EMC2_DEFAULT_NMLFILE "/home/lingchun/interpolation/temp/linuxcnc-mirror/configs/common/emc.nml"

/* Default nml file */
#define EMC2_DEFAULT_TOOLTABLE "/home/lingchun/interpolation/temp/linuxcnc-mirror/configs/sim/sim.tbl"

/* Directory for help files */
#define EMC2_HELP_DIR "/home/lingchun/interpolation/temp/linuxcnc-mirror/docs/help"

/* Prefix or RIP directory */
#define EMC2_HOME "/home/lingchun/interpolation/temp/linuxcnc-mirror"

/* Directory for images */
#define EMC2_IMAGE_DIR "/home/lingchun/interpolation/temp/linuxcnc-mirror"

/* Directory for tcl translation files */
#define EMC2_LANG_DIR "/home/lingchun/interpolation/temp/linuxcnc-mirror/src/objects"

/* Directory for nc files */
#define EMC2_NCFILES_DIR "/home/lingchun/interpolation/temp/linuxcnc-mirror/nc_files"

/* Directory for po/mo translation files */
#define EMC2_PO_DIR "/home/lingchun/interpolation/temp/linuxcnc-mirror/share/locale"

/* Directory of realtime system */
#define EMC2_RTLIB_DIR "/home/lingchun/interpolation/temp/linuxcnc-mirror/rtlib"

/* Directory for tcl scripts */
#define EMC2_TCL_DIR "/home/lingchun/interpolation/temp/linuxcnc-mirror/tcl"

/* Define to 1 if you have the <GL/glu.h> header file. */
#define HAVE_GL_GLU_H 1

/* Define to 1 if you have the <GL/gl.h> header file. */
#define HAVE_GL_GL_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define to 1 if you have the `GL' library (-lGL). */
#define HAVE_LIBGL 1

/* Define to 1 if you have the `intl' library (-lintl). */
/* #undef HAVE_LIBINTL */

/* Define to 1 if you have the <libintl.h> header file. */
#define HAVE_LIBINTL_H 1

/* Define to 1 if you have the `ncurses' library (-lncurses). */
#define HAVE_LIBNCURSES 1

/* Define to 1 if you have the `Xaw' library (-lXaw). */
#define HAVE_LIBXAW 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the <memory.h> header file. */
/* #undef HAVE_MEMORY_H */

/* Define to 1 if you have the <ncurses.h> header file. */
#define HAVE_NCURSES_H 1

/* Define to 1 if you have the 'readline' library (-lreadline) and required
   headers */
#define HAVE_READLINE /**/

/* Define to 1 if you have the <readline/history.h> header file. */
#define HAVE_READLINE_HISTORY_H 1

/* Define to 1 if you have the <readline/readline.h> header file. */
#define HAVE_READLINE_READLINE_H 1

/* Define to 1 if you have the `semtimedop' function. */
#define HAVE_SEMTIMEDOP 1

/* Define to 1 if you have the `setlocale' function. */
#define HAVE_SETLOCALE 1

/* Define to 1 if you have the `sincos' function. */
/* #undef HAVE_SINCOS */

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
/* #undef HAVE_STDLIB_H */

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
/* #undef HAVE_STRING_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
/* #undef HAVE_SYS_STAT_H */

/* Define to 1 if you have the <sys/types.h> header file. */
/* #undef HAVE_SYS_TYPES_H */

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <tcl.h> header file. */
/* #undef HAVE_TCL_H */

/* Define to 1 if you have the <tk.h> header file. */
/* #undef HAVE_TK_H */

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Define to 1 if you have the <X11/Xaw/XawInit.h> header file. */
#define HAVE_X11_XAW_XAWINIT_H 1

/* Define to 1 if you have the <X11/Xmu/Xmu.h> header file. */
#define HAVE_X11_XMU_XMU_H 1

/* Define to 1 if you have the `__sincos' function. */
/* #undef HAVE___SINCOS */

/* Extension for realtime modules */
#define MODULE_EXT ".so"

/* Define to 1 if asm/msr.h is usable and defines rdtscll */
/* #undef MSR_H_USABLE */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "emc-developers@lists.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "EMC2"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "EMC2 2.4.6"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "emc2"

/* Define to the home page for this package. */
#define PACKAGE_URL ""

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.4.6"

/* Required kernel version */
/* #undef RTAPI_KERNEL_VERSION */

/* Realtime system is RTAI */
/* #undef RTAPI_RTAI */

/* Realtime system is RTL */
/* #undef RTAPI_RTL */

/* Realtime system is simulated */
#define RTAPI_SIM /**/

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE
#endif


#endif

